export { SpinoramaSettings, SpinoramaProps } from './Spinorama/index.types'
export { SpinoramaWrapperProps } from './Wrapper/index.types'
export { SpinoramaItemProps } from './Item/index.types'
export { SpinoramaActionsProps } from './Actions/index.types'
export { SpinoramaButtonsProps } from './Buttons/index.types'
export { SpinoramaNextProps } from './Next/index.types'
export { SpinoramaPrevProps } from './Prev/index.types'
export { SpinoramaThumbnailsProps } from './Thumbnails/index.types'
export { SpinoramaThumbnailProps } from './Thumbnail/index.types'
